  name: Setup Python
  uses: actions/setup-python@v4.5.0
  with:
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
          SRC_ORG: ${{ secrets.SRC_ORG }}
          DST_ORG: ${{ secrets.DST_ORG }}
        run: |
            pip install pygithub
            python -u mirror_github_org.py --full-run

    
