name: Full update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  full-update:
    runs-on: ubuntu-latest
    steps:
      - - name: Setup Python
          uses: actions/setup-python@v4.5.0
          with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '4.5'
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
          SRC_ORG: ${{ secrets.SRC_ORG }}
          DST_ORG: ${{ secrets.DST_ORG }}
        run: |
            pip install pygithub
            python -u mirror_github_org.py --full-run
